"""add pr unique constraint

Revision ID: 854f0707af31
Revises: c3162b03dc3c
Create Date: 2026-02-23 11:54:29.265919

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '854f0707af31'
down_revision: str | Sequence[str] | None = 'c3162b03dc3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pull_requests_repo_pr', 'pull_requests', ['repo_id', 'pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pull_requests_repo_pr', 'pull_requests', type_='unique')
    # ### end Alembic commands ###
