"""add repo+pr uniqueness

Revision ID: a95cba69544d
Revises: 854f0707af31
Create Date: 2026-02-23 11:59:33.152200

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a95cba69544d'
down_revision: str | Sequence[str] | None = '854f0707af31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_repos_tenant_owner_name', 'repos', ['tenant_id', 'owner', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repos_tenant_owner_name', 'repos', type_='unique')
    # ### end Alembic commands ###
